# ALinux container configuration
container.id=alpine
container.hostname=alpine-android
container.user=root
container.workdir=/root
ssh.port=2224
ssh.password=root
image.url=https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/aarch64/alpine-minirootfs-3.21.0-aarch64.tar.gz
